### ISSUE TITLE
Issue on installing PIL ?

### ISSUE THREAD

**Issue by Aju100** [geekyarthurs/samueledits#3]
@geekyarthurs bro, I have a problem with installing **PIL** package. **Pillow** and **PIL** are the same or something. I get a little bit to confuse in it, bro. 
When I follow above your readme documentation.
`pip install pil`
![samuel](https://user-images.githubusercontent.com/29862610/65380224-3e7dad00-dcf6-11e9-8dfa-7aa41ba61439.png)
**My local environment**
- Ubuntu
- Python 3.x

**Comment by geekyarthurs** [comment]
They’re same.
